#!/usr/bin/env python3
"""Export one PE->RE->PE cycle as an RDF/JSON-LD trace graph — M4.

    scripts/export-runtime-trace.py --engine cpp-1 --out trace.ttl
    scripts/export-runtime-trace.py --engine cpp-1 --push --out trace.ttl --jsonld trace.jsonld
    scripts/export-runtime-trace.py --engine cpp-1 --check-joinability

M2 gave the integration paths a vocabulary; M3 proved the authored corpus
against it. Both are static. This points the same vocabulary at what actually
ran, so a trace and the corpus it came from merge into one graph.

## The join was already there

The engines emit `GET /api/audit/semantics` records carrying `machineIri`,
`sequenceIri`, `stepIri` and `determinationIri` that are **byte-identical** to
the IRIs `generate-owl.py` writes into the ABox. So M4's joinability criterion
is not a thing to build; it is a thing to verify and then keep verified.

What this adds is the other four event kinds, which have surfaces but no RDF:
PE source writes and pushes from the PE, dispatches from the dispatch ledger,
and completion write-backs.

## Reading, never driving, unless asked

By default this reads what the universe has already recorded. `--push` issues
one `POST /api/push` first, because a freshly started universe has an empty
audit surface and "export produced nothing" would otherwise be indistinguishable
from "export is broken" — the failure this project keeps rediscovering.

## What it refuses to invent

Three of M4's required identifiers are not emitted by any runtime surface today:
a push id, a correlation id on PE source writes, and the output region on a
sequence observation. They are reported as gaps, per event kind, with counts.
They are **not** synthesised. A generated push id would look exactly like a real
one and would join two events that nothing actually connected.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = "http://127.0.0.1:5999/re-registry.json"

TRACE_NS = "https://realityengine.example.org/runtime-trace"
ENGINE_NS = "https://realityengine.example.org/engines"
PROVIDER_NS = "https://realityengine.example.org/providers"


def get(url: str, timeout: int = 60):
    with urllib.request.urlopen(url, timeout=timeout) as r:
        return json.loads(r.read())


def post(url: str, body: dict, timeout: int = 120):
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def esc(value) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")


def slug(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]", "-", str(value))[:120]


class Trace:
    """Accumulates triples and the gaps found while building them."""

    def __init__(self, run_id: str, engine_id: str):
        self.run_id = run_id
        self.engine_id = engine_id
        self.blocks: list[str] = []
        self.gaps: dict[str, int] = {}
        self.counts: dict[str, int] = {}
        self.unjoined: list[str] = []

    def gap(self, what: str, n: int = 1) -> None:
        self.gaps[what] = self.gaps.get(what, 0) + n

    def count(self, kind: str, n: int = 1) -> None:
        self.counts[kind] = self.counts.get(kind, 0) + n

    def add(self, subject: str, statements: list[str]) -> None:
        body = " ;\n    ".join(s for s in statements if s)
        self.blocks.append(f"{subject}\n    {body} .\n")

    def ttl(self) -> str:
        head = [
            f"# Runtime trace, run {self.run_id}, engine {self.engine_id}.",
            "# Generated by scripts/export-runtime-trace.py — M4 of the Semantic OWL roadmap.",
            "# Merge with semantics/ontology/re-core.ttl and the machine ABoxes; every",
            "# event joins to a corpus machine IRI or to an explicit external-provider IRI.",
            "",
            "@prefix re:   <https://realityengine.example.org/ontology/re-core#> .",
            "@prefix owl:  <http://www.w3.org/2002/07/owl#> .",
            "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
            "@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .",
            "@prefix prov: <http://www.w3.org/ns/prov#> .",
            f"@prefix t:    <{TRACE_NS}/{self.run_id}#> .",
            f"@prefix eng:  <{ENGINE_NS}#> .",
            f"@prefix prov_: <{PROVIDER_NS}#> .",
            "",
        ]
        return "\n".join(head) + "\n".join(self.blocks)

    def jsonld(self) -> str:
        """JSON-LD with the same content, for consumers that will not parse Turtle."""
        return json.dumps({
            "@context": {
                "re": "https://realityengine.example.org/ontology/re-core#",
                "prov": "http://www.w3.org/ns/prov#",
                "t": f"{TRACE_NS}/{self.run_id}#",
                "eng": f"{ENGINE_NS}#",
            },
            "@id": f"t:run",
            "@type": "re:TraceRun",
            "re:runId": self.run_id,
            "re:engineId": self.engine_id,
            "re:counts": self.counts,
            "re:gaps": self.gaps,
            "@graph": "see the Turtle serialisation; this document is the run header",
        }, indent=2)


def approved_mapping_for(sensor_id: str) -> str | None:
    """The integrations.json sourceMappings id whose template this sensor matches.

    Templates carry `{placeholder}` segments — `acp.openclaw.{agent}.completion`
    — so the match is on shape, not equality. A sensor matching none is reported
    as a gap rather than given a mapping: an unapproved write must stay visibly
    unapproved, which is M3's R5 and M5's forbidden-endpoint check.
    """
    cfg = REPO_ROOT.parent / "RealityEngine_CI" / "config" / "integrations.json"
    if not cfg.is_file():
        return None
    try:
        mappings = json.loads(cfg.read_text()).get("sourceMappings", [])
    except (OSError, ValueError):
        return None
    for m in mappings:
        tpl = m.get("sensorIdTemplate")
        if not tpl:
            continue
        pattern = re.sub(r"\\\{[^}]*\\\}", r"[^.]+", re.escape(tpl))
        if re.fullmatch(pattern, sensor_id):
            return m.get("id")
    return None


def provider_of(machine_name: str | None) -> str | None:
    """The external provider a runtime-injected machine came from, if any.

    A machine the engine holds but the corpus does not define is named with a
    provider prefix — `localai/agent_activity_classifier`. Seven such machines
    are live in this deployment, supplied by localAIStack rather than authored
    in `machines/`. They are not corpus drift and not an export defect; they are
    the case M4's joinability criterion names second.
    """
    if not machine_name or "/" not in machine_name:
        return None
    prefix = machine_name.split("/", 1)[0]
    return prefix if prefix and not prefix.startswith(" ") else None


def corpus_machine_iris() -> dict[str, str]:
    """machineName -> the corpus machine IRI, read from the generated ABoxes.

    The join goes through the **name**, not the id. Machine ids are re-minted by
    each runtime on import, so `machine-falldetection` on cpp-1 and on lsp-1 are
    different strings for the same machine; `machineName` is the only key stable
    across engines. That is the same lesson the CES contract recorder learned —
    keying a fingerprint on a per-runtime id measures the runtime, not the
    corpus.
    """
    out: dict[str, str] = {}
    abox = REPO_ROOT / "semantics" / "abox"
    for path in abox.rglob("*.ttl"):
        text = path.read_text()
        m = re.search(r'^@prefix m:\s+<([^>]+)>', text, re.M)
        if not m:
            continue
        base = m.group(1)
        label = re.search(r'^m:machine\n(?:.*\n)*?\s+rdfs:label "([^"]+)"', text, re.M)
        if label:
            out[label.group(1)] = f"{base}machine"
    return out


def export(engine_id: str, re_url: str, pe_url: str, do_push: bool) -> Trace:
    run_id = f"{engine_id}-{int(time.time())}"
    tr = Trace(run_id, engine_id)
    corpus_iris = corpus_machine_iris()

    push_result = None
    if do_push:
        # A freshly started universe has an empty audit surface, and "exported
        # nothing" must not be confusable with "export is broken".
        push_result = post(f"{pe_url}/api/push", {})

    state = get(f"{pe_url}/api/state")
    sources = get(f"{pe_url}/api/sources")
    sources = sources if isinstance(sources, list) else sources.get("sources", [])
    audit = get(f"{re_url}/api/audit/semantics").get("records", [])
    try:
        ledger = get(f"{pe_url}/api/dispatch/ledger")
    except urllib.error.HTTPError:
        ledger = {"records": []}
    dispatches = ledger.get("records", [])

    # ── The run ──────────────────────────────────────────────────────────────
    tr.add("t:run", [
        "a owl:NamedIndividual , re:TraceRun",
        f'rdfs:label "Runtime trace {esc(run_id)}"',
        f're:runId "{esc(run_id)}"',
        f're:engineId "{esc(engine_id)}"',
        f"re:observedOnEngine eng:{slug(engine_id)}",
        f're:observedAtMs "{int(time.time() * 1000)}"^^xsd:long',
    ])
    tr.add(f"eng:{slug(engine_id)}", [
        "a owl:NamedIndividual , prov:Agent",
        f'rdfs:label "{esc(engine_id)}"',
        f're:engineId "{esc(engine_id)}"',
        f're:targetEndpoint "{esc(re_url)}"^^xsd:anyURI',
    ])

    # ── PE push ──────────────────────────────────────────────────────────────
    # No runtime surface emits a push id. The step counter plus the engine is
    # the only stable identity available, and it is labelled as derived rather
    # than passed off as one the PE issued.
    step = state.get("globalStep")
    tr.gap("push id (no runtime surface emits one; derived from globalStep)")
    push_iri = f"t:push-{slug(str(step))}"
    tr.add(push_iri, [
        "a owl:NamedIndividual , re:PerceptionPush",
        f'rdfs:label "push at step {esc(step)} to {esc(re_url)}"',
        f're:pushId "{esc(engine_id)}-step-{esc(step)}"',
        f're:targetEndpoint "{esc(re_url)}"^^xsd:anyURI',
        f're:matchAlgorithm "{esc(state.get("matchAlgorithm"))}"' if state.get("matchAlgorithm") else "",
        f"re:atTick {step}" if isinstance(step, int) else "",
        f're:observedAtMs "{int(state.get("lastPush") or 0)}"^^xsd:long',
        "re:inTraceRun t:run",
    ])
    tr.count("re:PerceptionPush")

    # ── PE source writes ─────────────────────────────────────────────────────
    active = [s for s in sources if s.get("active")]
    for src in active:
        region = src.get("region") or {}
        offset, length = region.get("offset"), region.get("length")
        machine_iri = None
        # A source names a machine by runtime id and by name. Machine ids are
        # re-minted per runtime; machineName is the only stable key, so the
        # corpus join goes through the name.
        name = src.get("machineName")
        if name:
            machine_iri = corpus_iris.get(name)
        sid = slug(src.get("id", "unknown"))
        # A source whose values arrived from outside the engine is a completion
        # write-back, not a perception event: it is the last hop of an
        # integration path, and re:SourceMappingWrite is the class M2 gave it.
        # Classifying both as re:PerceptionEvent would have made a completion
        # indistinguishable from a test sequence, which is exactly the
        # distinction M5's acceptance criteria turn on.
        is_completion = (src.get("origin") == "external"
                         or str(src.get("sensorId") or "").startswith(("acp.", "agent.", "localai.")))
        cls = "re:SourceMappingWrite" if is_completion else "re:PerceptionEvent"
        stmts = [
            f"a owl:NamedIndividual , {cls}",
            f'rdfs:label "{"completion write-back" if is_completion else "PE source write"} {esc(src.get("id"))}"',
            f're:sourceId "{esc(src.get("id"))}"',
            f"re:writeOffset {offset}" if isinstance(offset, int) else "",
            f"re:writeLength {length}" if isinstance(length, int) else "",
            f're:sensorId "{esc(src.get("sensorId"))}"' if src.get("sensorId") else "",
            f're:observedAtMs "{int(src.get("lastUpdated") or 0)}"^^xsd:long',
            "re:inTraceRun t:run",
        ]
        if machine_iri:
            stmts.append(f"re:forMachine <{machine_iri}>")
        elif provider_of(name):
            # M4's joinability criterion is "a machine IRI **or an explicit
            # external-provider IRI**", and this is the second case, not a
            # failure of the first. These machines are real, live and loaded —
            # localAIStack injects them at runtime — but they are not corpus
            # machines and have no ABox, so there is no machine IRI to point at.
            # Attributing them to the provider that supplied them is the true
            # statement; silently dropping them would understate the trace, and
            # minting a corpus IRI for them would assert a machine the corpus
            # does not define.
            pid = provider_of(name)
            stmts.append(f"re:invokesProvider prov_:{slug(pid)}")
            tr.add(f"prov_:{slug(pid)}", [
                "a owl:NamedIndividual , re:IntegrationProvider",
                f'rdfs:label "{esc(pid)}"',
                f're:providerId "{esc(pid)}"',
            ])
            tr.gap(f"runtime machine not in the corpus, attributed to provider '{pid}'")
        elif is_completion:
            # A completion write-back has no machine of its own: it is an
            # external producer writing into a reserved band, and the producer
            # is what it joins to. The sensor id names it — acp.openclaw.* is
            # OpenClaw, localai.* is localAIStack.
            pid = (str(src.get("sensorId") or "").split(".") or ["external"])[0]
            if pid == "acp":
                pid = str(src.get("sensorId") or "").split(".")[1] if "." in str(src.get("sensorId") or "") else "acp"
            stmts.append(f"re:writtenBy prov_:{slug(pid)}")
            tr.add(f"prov_:{slug(pid)}", [
                "a owl:NamedIndividual , re:IntegrationProvider",
                f'rdfs:label "{esc(pid)}"',
                f're:providerId "{esc(pid)}"',
            ])
        else:
            tr.unjoined.append(f"PE source write {src.get('id')}: "
                               f"machineName {name!r} matches no corpus machine "
                               f"and names no provider")
        if is_completion:
            # The mapping the write exercised, resolved from the sensor id
            # against the deployment's approved templates. Stated only when it
            # resolves: naming a mapping the deployment does not approve would
            # assert an authorisation that does not exist.
            mapping = approved_mapping_for(str(src.get("sensorId") or ""))
            if mapping:
                mid = f"t:mapping-{slug(mapping)}"
                stmts.append(f"re:writesThroughMapping {mid}")
                tr.add(mid, [
                    "a owl:NamedIndividual , re:CompletionMapping",
                    f'rdfs:label "{esc(mapping)}"',
                    f're:sensorId "{esc(src.get("sensorId"))}"',
                    f"re:completionOffset {offset}" if isinstance(offset, int) else "",
                    f"re:completionLength {length}" if isinstance(length, int) else "",
                ])
            else:
                tr.gap(f"completion sensor '{src.get('sensorId')}' matches no approved "
                       f"sourceMappings template")
        elif not src.get("correlationId"):
            tr.gap("correlation id on PE source writes")
        tr.add(f"t:src-{sid}", stmts)
        tr.count(cls)

    # ── RE sequence observations ─────────────────────────────────────────────
    for i, rec in enumerate(audit):
        m_iri = rec.get("machineIri")
        stmts = [
            "a owl:NamedIndividual , re:SequenceObservation",
            f'rdfs:label "{esc(rec.get("machineName"))} / {esc(rec.get("sequenceId"))}"',
            f"re:forMachine <{m_iri}>" if m_iri else "",
            f"re:observedSequence <{rec['sequenceIri']}>" if rec.get("sequenceIri") else "",
            f"re:observedStep <{rec['stepIri']}>" if rec.get("stepIri") else "",
            f"re:recordsDetermination <{rec['determinationIri']}>" if rec.get("determinationIri") else "",
            f're:actionCode "{esc(rec.get("actionCode"))}"' if rec.get("actionCode") else "",
            f're:observedAtMs "{int(rec.get("at") or 0)}"^^xsd:long',
            f"re:pushedVector {push_iri}",
            "re:inTraceRun t:run",
        ]
        if not m_iri:
            tr.unjoined.append(f"sequence observation {i}: no machineIri")
        if rec.get("ragStatus"):
            rag = str(rec["ragStatus"]).upper()
            if rag in ("GREEN", "AMBER", "RED"):
                stmts.append(f"re:hasRagStatus re:{rag}")
        tr.add(f"t:obs-{i:05d}", stmts)
        tr.count("re:SequenceObservation")
    if audit and not any(r.get("outputRegion") for r in audit):
        tr.gap("output region on sequence observations (M4 names it; no engine emits it)")

    # ── Dispatches ───────────────────────────────────────────────────────────
    for i, rec in enumerate(dispatches):
        env = rec.get("envelope") or {}
        ces = env.get("ces") or {}
        disp = env.get("dispatch") or {}
        endpoint = (disp.get("endpoint") or {})
        kind = endpoint.get("kind") or "unknown"
        name = ces.get("machineName")
        out = (ces.get("perceptualMapping") or {}).get("output") or {}

        # ACP/OpenClaw and MCP/localAI are different classes in the vocabulary,
        # and the ledger says which by the endpoint kind it recorded.
        is_acp = kind in ("acp", "openclaw") or "openclaw" in str(disp.get("agent", "")).lower()
        cls = "re:ACPDispatch" if is_acp else "re:DispatchRecord"
        provider = f"prov_:{slug(kind)}"
        stmts = [
            f"a owl:NamedIndividual , {cls}",
            f'rdfs:label "dispatch {esc(rec.get("correlationId"))}"',
            f're:dispatchId "{esc(rec.get("id") or rec.get("correlationId"))}"',
            f're:correlationId "{esc(rec.get("correlationId"))}"' if rec.get("correlationId") else "",
            f're:observedAtMs "{int(rec.get("createdAt") or 0)}"^^xsd:long',
            f"re:invokesProvider {provider}" if not is_acp else "",
            f're:noWaitDispatch true' if is_acp else "",
            f"re:writeOffset {out['offset']}" if isinstance(out.get("offset"), int) else "",
            f"re:writeLength {out['length']}" if isinstance(out.get("length"), int) else "",
            "re:inTraceRun t:run",
        ]
        machine_iri = None
        if name:
            machine_iri = corpus_iris.get(name)
        if machine_iri:
            stmts.append(f"re:forMachine <{machine_iri}>")
        else:
            # An explicit external-provider IRI satisfies M4's joinability
            # criterion just as a machine IRI does — the criterion is "joins to
            # a machine IRI *or* an explicit external-provider IRI".
            stmts.append(f"re:invokesProvider {provider}")
        tr.add(f"t:disp-{i:05d}", stmts)
        tr.add(provider, [
            "a owl:NamedIndividual , re:IntegrationProvider",
            f'rdfs:label "{esc(kind)}"',
            f're:providerId "{esc(kind)}"',
            f're:integrationEndpoint "{esc(endpoint.get("url") or "")}"^^xsd:anyURI'
            if endpoint.get("url") else "",
        ])
        tr.count(cls)

    if push_result is not None:
        d = push_result.get("dispatch") or {}
        if d.get("mode") == "dry-run":
            tr.gap("dispatch ran in dry-run mode: no completion write-back to trace")

    return tr


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--registry", default=DEFAULT_REGISTRY,
                    help="instance registry URL (default: the local one)")
    ap.add_argument("--engine", default=None, help="instance id, e.g. cpp-1")
    ap.add_argument("--push", action="store_true",
                    help="drive one POST /api/push before reading")
    ap.add_argument("--out", type=Path, help="write Turtle here")
    ap.add_argument("--jsonld", type=Path, help="write a JSON-LD run header here")
    ap.add_argument("--check-joinability", action="store_true",
                    help="exit non-zero if any event joins to nothing")
    args = ap.parse_args()

    try:
        reg = get(args.registry, timeout=20)
    except Exception as e:
        print(f"export-runtime-trace: no instance registry at {args.registry} ({e})",
              file=sys.stderr)
        return 2
    instances = {i["id"]: i for i in reg.get("instances", [])}
    if not instances:
        print("export-runtime-trace: the instance registry names no instances", file=sys.stderr)
        return 2
    engine_id = args.engine or sorted(instances)[0]
    if engine_id not in instances:
        print(f"export-runtime-trace: no instance '{engine_id}' "
              f"(have {sorted(instances)})", file=sys.stderr)
        return 2
    inst = instances[engine_id]

    tr = export(engine_id, inst["re_url"].rstrip("/"), inst["pe_url"].rstrip("/"), args.push)

    if args.out:
        args.out.write_text(tr.ttl())
    if args.jsonld:
        args.jsonld.write_text(tr.jsonld())

    print(f"export-runtime-trace: run {tr.run_id} on {engine_id}")
    for k in sorted(tr.counts):
        print(f"  {tr.counts[k]:6}  {k}")
    total = sum(tr.counts.values())
    joined = total - len(tr.unjoined)
    print(f"  joinability: {joined}/{total} events join to a machine IRI or a provider IRI")
    for g, n in sorted(tr.gaps.items()):
        print(f"  GAP     {g}" + (f" (x{n})" if n > 1 else ""))
    if args.out:
        print(f"  wrote   {args.out} ({len(tr.ttl().splitlines())} lines)")
    if args.jsonld:
        print(f"  wrote   {args.jsonld}")

    if args.check_joinability and tr.unjoined:
        print(f"\nexport-runtime-trace: FAIL — {len(tr.unjoined)} event(s) join to nothing")
        for u in tr.unjoined[:20]:
            print(f"  {u}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
