#!/bin/bash
# Architecture-aware corpus validation before seeding or accepting new domains.
#
# This script is the gate the domain-addition protocol runs on. What a domain
# must supply, what each gate below proves, and when a domain must extend the
# regression corpus are specified in:
#
#     RealityEngine_CI/MACHINE_CONCEPT.md  §9  Adding a Domain
#
# Default mode is compatibility-safe: hard schema errors fail the build, while
# migration gaps such as legacy dispatchableAgent without agentBinding are
# reported as warnings.  Set STRICT_DOMAIN_CONTRACT=1 to make warnings fail.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ARGS=("--machines-root" "$REPO_ROOT/machines")
if [ "${STRICT_DOMAIN_CONTRACT:-0}" != "0" ]; then
  ARGS+=("--strict")
fi

python3 "$SCRIPT_DIR/audit-corpus.py" "${ARGS[@]}" "$@"
python3 "$SCRIPT_DIR/inventory-semantic-buses.py" --check --summary-only
python3 "$SCRIPT_DIR/build-corpus-index.py" --check
python3 "$SCRIPT_DIR/build-region-allocation.py" --check

# Arbitration gate (docs/ARBITER_CONTRACT.md §5): a universal-vector position
# written by more than one contributor — machine final Reality Events and PE
# sources alike — must declare how it resolves. An undeclared contended cell
# would fall through to merge order, which is stable and therefore reproduces a
# wrong resolution as if it were correct.
python3 "$SCRIPT_DIR/build-arbitration-registry.py" --check

# OWL semantic gates (docs/SEMANTIC_OWL_ROADMAP.md): checked-in ABox drift
# for exemplar domains, corpus-wide manifest drift, and — when ROBOT is
# installed (CI) — reasoner consistency.
python3 "$SCRIPT_DIR/backfill-lane-contracts.py" --check
# --all, not a nominated domain. This read `--domain health-personal` and so
# checked one domain out of the manifest: every domain added since shipped
# without its ABox ever being gated, and the next one would have too.
python3 "$SCRIPT_DIR/generate-owl.py" --all --check --strict-actions
python3 "$SCRIPT_DIR/generate-owl.py" --manifest-check --strict-actions
bash "$SCRIPT_DIR/reason-owl.sh"
# --check, not --write. A generator run in write mode inside a validation gate
# cannot fail: it rewrites the artifact to match whatever the corpus now says
# and exits 0, so drift is absorbed silently and the gate reports health it
# never established. Regenerate deliberately with the :write npm scripts.
#
# The one exception is ABSENCE, and only for the two artifacts under
# semantics/lanes/. That directory is gitignored: lane-graph.ttl and
# decision-table.json are deployment artifacts, generated by the lane that needs
# them and never maintained in git. So a fresh checkout has neither, and every
# cold-start regression worktree is a fresh checkout — the gate was asking
# origin/main for files that cannot exist there, and failed by construction on
# every lane, every run, before the universe ever started.
#
# Absence is not drift. There is nothing to have drifted from, so generating a
# missing one establishes the baseline rather than absorbing a difference. An
# artifact that EXISTS is never regenerated here, which is what keeps the rule
# above intact: a stale one still reaches --check, and still fails.
bootstrap_deployment_artifact() {  # generator-script output-path
  local script="$1" output="$2"
  if [ ! -e "$REPO_ROOT/$output" ]; then
    echo "$(basename "$script" .py): $output absent — generating (deployment artifact, not tracked)"
    python3 "$SCRIPT_DIR/$script" --write >/dev/null
  fi
}
bootstrap_deployment_artifact project-lanes.py semantics/lanes/lane-graph.ttl
bootstrap_deployment_artifact compile-decision-table.py semantics/lanes/decision-table.json

python3 "$SCRIPT_DIR/project-lanes.py" --check
python3 "$SCRIPT_DIR/compile-decision-table.py" --check
bash "$SCRIPT_DIR/validate-guardrails.sh"

# Unit-vocabulary gates. Both shipped with verification modes that no gate
# invoked, so neither had ever run against the corpus (RealityEngine_CI#352
# is the same finding in the CI repo).
python3 "$SCRIPT_DIR/extract-qudt-subset.py" --source "$REPO_ROOT/.qudt-cache" --check
python3 "$SCRIPT_DIR/ucum.py" --scan "$REPO_ROOT/domains/region-allocation.json"

# Inventory gate: every generator on disk is declared, scoped to a corpus, and
# reachable from a gate. This is what keeps a new domain's generator from
# arriving unwired — the failure this file could not previously detect.
python3 "$SCRIPT_DIR/check-generators.py" --check

# JSON-Schema enforcement (machines + registries + trigger files vs schemas/).
# Requires devDependencies (ajv); skip with a clear notice if not installed so
# the Python audit still runs in minimal environments.
if [ -d "$REPO_ROOT/node_modules/ajv" ]; then
  node "$SCRIPT_DIR/validate-schemas.mjs"
else
  echo "validate-schemas: SKIPPED (run 'npm install' to enable ajv JSON-Schema enforcement)"
fi
